test: main.o inputf.o printf.o
	gcc -o test test01_main.o test01_printf.o test01_inputf.o

main.o: test01_main.c
	gcc -c test01_main.c

inputf.o: test01_inputf.c
	gcc -c test01_inputf.c

prinrf.o: test01_printf.c
	gcc -c test01_printf.c
